move sprite data out of main program
SecKC/Badge-DC25 pull request #1
Opened 2017-07-12 19:28 UTC by pecord

I was researching how hard it would be to get flappy bird onto the badge and I found a [project](https://github.com/huytd/arduino-flappybird/blob/master/Sprite.h) where they put the image data in a separate file.

* moved image data out of `ino` file
* tailing white-space cleanup (atom does that on save)

2017-07-13 05:10 UTC, patrickrb requested changes

2017-07-13 05:10 UTC, patrickrb commented on BadgeCode/BadgeCode.ino
> +#include "Sprite.h"
Should probably match the <> above

`#include <Sprite.h>`

2017-07-13 15:11 UTC, pecord commented on BadgeCode/BadgeCode.ino
> +#include "Sprite.h"
https://stackoverflow.com/questions/3162030/difference-between-angle-bracket-and-double-quotes-while-including-heade#3162067

>It's compiler dependent. That said, in general using " prioritizes headers in the current working directory over system headers.  <> usually is used for system headers.

2017-07-17 00:26 UTC, rixon commented
Thanks for this code cleanup and brief discussion.  👍

2017-07-17 00:26 UTC, merged